### ISSUE TITLE
lollipop 1.15.2-1.0.4 crashes dedicated server Forge 1.15.2 build 31.1.14

### ISSUE THREAD

**Issue by kreezxil** [xieaoDev/Lollipop#2]
Notes:
     you let a client side thing slip thru to the server side

crash report:
http://paste.ubuntu.com/p/76zjYSQ4Hs/

fml server latest:
http://paste.ubuntu.com/p/4Ghm5tbbBf/

**Comment by owmii** [comment]
Test the generator with an other mod cables than flux and see what happen, because the crash report says that the tile entity with the id `flux:energy_cable` caused the crash.
Also the crash say is Attempted to load class `net/minecraft/client/gui/screen/Screen` for the `Server side` but there is no screen classes included in the generator class or super classes.

**Comment by owmii** [comment]
Just found the problem and fixed in v1.0.4, thanks for reporting!
